### ISSUE TITLE
Issueベースの開発レビュー依頼

### ISSUE THREAD

**Issue by tuyotuyousatyann** [tuyotuyousatyann/project#35]
# 概要
### MVPリリース時
- [ ] 全国のプライベートサウナを一覧で閲覧
- [ ] 詳細検索機能
- [ ] 新規ユーザー登録機能
- [ ] ログイン機能
- [ ] パスワード変更機能
-  [ ] メールアドレス変更機能
-  [ ] ログアウト機能
-  [ ] プロフィール機能
-  [ ] ログイン時の機能
-  [ ] お気に入り機能
-  [ ] お気に入り解除機能
- [ ] サ活記録投稿機能

### 本リリース時
- [ ] ヘルス情報　サウナの正しい入り方・得られる効能などをまとめた記事の閲覧
- [ ] 新規登録機能【SNS連携(Twitter)】
- [ ] SNS認証解除機能
- [ ] パーソナライズされたレコメンデーション: ユーザーの過去の行動や好みに基づいて、個々のユーザーに合わせたサウナ施設の推薦を行う機能

### MVPリリース時
- [ ] トップページ
- [ ] 新規会員登録ページ
- [ ] ログインページ
- [ ] パスワードリセット申請ページ
- [ ] パスワード更新ページ
- [ ] プロフィールページ
- [ ] プロフィール編集ページ
- [ ] サ活記録投稿ページ
- [ ] 登録済みのお気に入り施設ページ
- [ ] 投稿済みのサ活記録ページ
- [ ] 検索結果を一覧で表示するページ
- [ ] クリックした施設の詳細を表示するページ
- [ ] ログイン成功後のページ

### 本リリース時
- [ ] ヘルス情報（サウナの正しい入り方・得られる効能などをまとめた記事）の閲覧ページ
- [ ] 新規登録ページに追記（SNS連携でTwitterを選択することができる）
- [ ] ユーザの好みに合わせたサウナ施設の紹介

**Comment by Tsuchiya2** [comment]
ご提出ありがとうございます。
以下コメントになります。


ストーリーポイント5のissueがやや多い印象を受けました。おそらく見通しがつきにくいものにポイント5をつけられているかとお見受けしました。ストーリーポイント1,2くらいになるまで、細分化すると何が不明確で、何は明確になっているかが可視化されますし、進捗を感じられながら開発を進められるかと思います。

**Comment by Tsuchiya2** [comment]
良いと思います！LGTMです

**Comment by tuyotuyousatyann** [comment]
ありがとうございます！！
